# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)





Manufacturer.destroy_all

manufacturer_bob = Manufacturer.create({name: "BOB", logo:"http://www.kidsathomecanada.com/Bob_Strollers_Logo.jpg"})
manufacturer_bugaboo = Manufacturer.create({name: "Bugaboo", logo:"http://www.brandsoftheworld.com/sites/default/files/styles/logo-thumbnail/public/0022/0419/brand.gif"})
manufacturer_firstyears = Manufacturer.create({name: "First Years", logo:"http://1.bp.blogspot.com/-6abYcHD5WE4/UQ8lb7aVfVI/AAAAAAAADb0/3kG_I10TU8I/s1600/first_years_logo3.jpg"})
manufacturer_4moms = Manufacturer.create({name: "4Moms", logo: "http://www.kiddies.co.uk/uploads/images/logos/4moms.png"})
manufacturer_mutsy = Manufacturer.create({name: "Mutsy", logo: "http://4.bp.blogspot.com/-QzSCmz24Ylo/TyvO_3mMfdI/AAAAAAAAFI4/K_bkngUuCcU/s1600/logo+mutsy.jpg"})
manufacturer_pegperego = Manufacturer.create({name: "PegPerego", logo: "http://www.simplybabyandkids.com/userfiles/image/peg-perego-logo.jpg"})

puts "manufacturer"

Category.destroy_all

category_babystroller = Category.create({name: "Baby Stroller"})
category_babymonitor = Category.create({name: "Baby Monitor"})
category_carseat = Category.create({name: "Car Seat"})

puts "categories created"

Model.destroy_all
# model_revolution = Model.create({manufacturer_id: manufacturer_bob.id})

model_revolution = Model.create({ name: "Revolution SE", model_number: "ST1023", manufacturer_id: manufacturer_bob.id, category_id: category_babystroller.id, photo_url: 'http://intheknowmom.net/wp-content/uploads/2012/10/Bob-Revolution-SE.jpg', description: "Designed with a pivoting front wheel and a lightweight frame, the BOB Revolution SE Stroller offers a smooth ride and is ideal for everyday activities and not-so-everyday adventures. The easy-to-fold frame and suspension system provide convenience and comfort that both you and your baby will appreciate. And the stroller is packed with extra features like a reclining seat and a adjustable, multi-position canopy."}),
model_revolutionse = Model.create({ name: "Revolution SE Duallie", model_number: "ST1043", manufacturer_id: manufacturer_bob.id, category_id: category_babystroller.id, photo_url: 'http://ecx.images-amazon.com/images/I/81JeQ-sKzeL._SL1500_.jpg', description: "Ideal for parents and caregivers of multiple children, the BOB Revolution SE Duallie Stroller offers a pivoting front wheel and a lightweight frame that's designed for two. The easy-to-fold frame and suspension system provide convenience and comfort that both you and your children will appreciate. And the stroller is packed with extra features like reclining seats and adjustable, multi-position canopies."}),
model_strollerfit =  Model.create({ name: "Stroller Strides Fitness Single", model_number: "ST1051", manufacturer_id: manufacturer_bob.id, category_id: category_babystroller.id, photo_url: 'http://rockinmama.net/wp-content/uploads/2009/06/IMG_2061-1024x768.jpg', description: "Include your children in your workout with BOB and the Stroller Strides Fitness Program. Equipped with a Stroller Strides Fitness Kit, including: BOB Handlebar Console, Stroller Strides Exercise Manual and exercise tubing, the Stroller Strides Fitness Stroller is your perfect workout companion. "}),
model_strollerstrides = Model.create({ name: "Stroller Strides Duallie", model_number: "ST1051", manufacturer_id: manufacturer_bob.id, category_id: category_babystroller.id, photo_url: 'http://www.bz2-img.com/images_customers/06/62/33564811_252162_full.jpg', description: "This BOB is ready to get physical with its state-of-the-art suspension system, easy-fold, lightweight design and revolutionary swiveling front wheel, which locks in place when you want to really pump up the pace. The Accessory Adapter feature quickly secures a BOB Infant Car Seat Adapter or Snack Tray."}),
model_motion = Model.create({ name: "Motion Single Stroller", model_number: "840625", manufacturer_id: manufacturer_bob.id, category_id: category_babystroller.id, photo_url: 'http://www.momtrends.com/wp-content/uploads/2013/04/BOBStroller.jpg', description: "Ideal for your family's daily activities, the Motion is the perfect complement to your BOB jogging stroller."}),
model_ironman = Model.create({ name: "Ironman", model_number: "ST1006", manufacturer_id: manufacturer_bob.id, category_id: category_babystroller.id, photo_url: 'http://www.walkingmama.net/wp-content/uploads/2011/10/ironman-ad.jpg', description: "Whether you're a track trainer, regular jogger or somewhere in between, the Ironman is built to go as fast and far as your running experience moves you. The fixed front wheel, 16 inch high pressure, low profile tires roll effortlessly on hard surfaces whether jogging leisurely or at training pace speeds. For baby, it's a smooth ride with a state-of-the-art suspension system, ultra-padded reclining seat and adjustable five-point padded harness."}),
model_revolutionce = Model.create({ name: "Revolution CE", model_number: "", manufacturer_id: manufacturer_bob.id, category_id: category_babystroller.id, photo_url: "http://www.babyviva.com/photos/product/giant/9995130S8907/stroller-finder/revolution-ce-stroller.jpg", description: "Designed with a pivoting front wheel and a lightweight frame, the BOB Revolution CE Stroller offers a smooth, safe ride and will fit right into your hectic, urban lifestyle. The easy-to-fold frame and suspension system provide convenience and comfort that both you and your baby will appreciate. And the stroller is packed with extra features like a reclining seat and an adjustable, multi-position canopy."}),
model_sport = Model.create({ name: "Sport Utility Stroller", model_number: "ST1001", manufacturer_id: manufacturer_bob.id, category_id: category_babystroller.id, photo_url: 'http://www.auntievis.com/data/shopcart7/image_db/Bobs%20Utility%20-%20Dualli.jpg', description: "No pavement? No problem. The rugged yet lightweight Sport Utility Stroller tackles even the toughest terrain.With the latest innovative features, the Sport Utility Stroller is perfect for any off-road strolling experience. Knobby tires and high-impact polymer composite wheels maximize traction. A fixed front wheel provides increased stability hiking, jogging or when the trail gets rough."}),
model_donkey = Model.create({ name: "Donkey", model_number: "ST1023", manufacturer_id: manufacturer_bugaboo.id, category_id: category_babystroller.id, photo_url: 'http://styleberryblog.com/wp-content/uploads/2011/11/double-strollers-1024x1024.jpg', description: "The Bugaboo Donkey is the convertible stroller for kid and goods that grows and flows with your family. Whether you have one kid, two kids or twins, one stroller fits all! In just three simple clicks, the Bugaboo Donkey converts from a full-size mono to a full-size duo stroller and back again. With its flexible luggage options, there's plenty of room for your goods too. Going around town has never been this easy."}),
model_bee = Model.create({ name: "Bee", model_number: "ST1023", manufacturer_id: manufacturer_bugaboo.id, category_id: category_babystroller.id, photo_url: "http://www.detode.com/wp-content/uploads/2013/02/27/Bugaboo-Bee-Stroller-Lining-3.jpg", description: "Ideal for family life in the city, the Bugaboo Bee is a compact, nimble stroller. The sleek, one-piece design collapses in a simple motion, while the four-wheel suspension and five-point harness provide a safe, comfortable ride. The stroller transitions smoothly from forward- to rear-facing and adapts to infant car seats, making it a complete travel system from birth through childhood."}),
model_cameleon = Model.create({ name: "Cameleon 3", model_number: "ST1023", manufacturer_id: manufacturer_bugaboo.id, category_id: category_babystroller.id, photo_url: "http://www.mommyguru.com/wp-content/uploads/2013/03/Bugaboo-Cameleon-3-with-bassinet.jpg", description: "The 3rd generation of the iconic all-in-one stroller is even more versatile, stylish and functional than ever before. Light and compact, it's also easy to lift and store. Suitable for a newborn or toddler, the multi-terrain Bugaboo Cameleon3 can seamlessly adapt to your journey whether that's through the city, woods, sand or snow."}),
model_transporter = Model.create({ name: "Transporter Light-Weight Stroller", model_number: "879142001110", manufacturer_id: manufacturer_mutsy.id, category_id: category_babystroller.id, photo_url: "http://www.shopbobbys.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/2/4/247578.jpg", description: "This light-weight, full-sized stroller is characterized by its ease of operation, a height adjustable push bar and its' extremely compact volume when folded. A tremendous value, the Transporter has a very deep and padded seat and adjustable footrest to be comfortably used by infants from 3 months through 55 pounds. The reclining seat and large, protective hood create a serene environment for napping."}),
model_riderlt = Model.create({ name: "4 Rider Light Stroller", model_number: "879142007198", manufacturer_id: manufacturer_mutsy.id, category_id: category_babystroller.id, photo_url: "http://strollersandprams.com/strollers/image/1028/stroller.jpg", description: "When it comes to maneuverability and function, the Mutsy 4 Rider Light Stroller provides incomparable benefits. Available in a variety of colors - with many optional accessories to chose from – you can create your own baby transport system. The ease with which it can be folded up and stored by pushing the handle down and the safety handle up is another benefit derived when utilizing this stroller. Due to its lightweight frame, it is easy to carry and has been designed for parents who are constantly on the go."}),
model_ridersingle = Model.create({ name: "4 Rider Single Spoke Stroller", model_number: "ST1023", manufacturer_id: manufacturer_mutsy.id, category_id: category_babystroller.id, photo_url: "http://www.sellsimilar.com/wp-content/uploads/2013/02/master_MUT009.jpg", description: "Mutsy 4 Rider Single Spoke Standard is an intelligently-designed stroller that provides comfort to kids. This stroller has a click mechanism that helps to easily transform from a front-facing buggy to rear facing, and it can also be converted into a bassinet."}),
model_ironmandual = Model.create({ name: 'Ironman Duallie', model_number: "ST1006", manufacturer_id: manufacturer_bob.id, category_id: category_babystroller.id, photo_url: 'http://3.bp.blogspot.com/_XvRkWEoPm3s/TAWYp2FoY5I/AAAAAAAAAOc/QIwMZPiWYm0/s1600/DSC_0032.JPG', description: "Whether you're a track trainer, regular jogger or somewhere in between, the Ironman is built to go as fast and far as your running experience moves you. The fixed front wheel, 16 inch high pressure, low profile tires roll effortlessly on hard surfaces whether jogging leisurely or at training pace speeds. For baby, it's a smooth ride with a state-of-the-art suspension system, ultra-padded reclining seat and adjustable five-point padded harness. The Accessory Adapter feature quickly secures a BOB Infant Car Seat Adapter or Snack Tray. The Ironman's easy-fold, lightweight frame packs up quick so you'll never be late for the race. Ultra-padded, adjustable reclining seat for enhanced seating comfort, five-point padded harness keeps your child comfortably secure."}),
model_missoni = Model.create({ name: 'Bugaboo Missoni Cameleon', model_number: "252", manufacturer_id: manufacturer_bugaboo.id, category_id: category_babystroller.id, photo_url: "http://media.tumblr.com/tumblr_lknxzvAajK1qc0c1k.jpg", description: "The Bugaboo + Missoni special collection features two tailored designs. A bright block print adorns the Bugaboo Cameleon sun canopy and bassinet apron, while vibrant zigzags decorate the Bugaboo Bee sun canopy. Each collection is completed with a knitted Missoni blanket. The luxury knitted blanket features Missoni's signature craftsmanship and quality."}),
model_indigo = Model.create({ name: 'Indigo', model_number: "Y11221", manufacturer_id: manufacturer_firstyears.id, category_id: category_babystroller.id, photo_url: "http://trus.imageg.net/graphics/media/trus/Aplusplus/2011/11468608/Lamaze-Indigo-Stroller-11468608-01.jpg", description: "The First Years Indigo Stroller-Easier for You, More Comfortable for your Baby! Finally a stroller that is durable and, yes, it really will comfortably fit your little one up to 50 lbs. The modular Euro styled design and contemporary fashions combined with our unique reversible seat will make people take a second look! Keep your eye on your infant simply by releasing the seat and turning it to the rear facing mode. You can watch over your little one and they can watch over you."}),
model_burst = Model.create({ name: 'Burst', model_number: "Y60001", manufacturer_id: manufacturer_firstyears.id, category_id: category_babystroller.id, photo_url: "http://www.capitalkidz.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/f/i/first_years_burst_grey.jpg", description: "The First Years Burst stroller designed for your comfort and convenience. You can use the Burst stroller for your newborn and keep using it as your toddler grows, up to 50 pounds. This stroller is designed with both you and your baby in mind. For you, the large upper parent storage has plenty of room to keep your keys, phone and much more and the large lower basket is easy to access and has room for your diaper bag and much more. For your little one, there is a large child's tray with room for your sippy cup and snacks. "}),
model_origami = Model.create({ name: 'Origami', model_number: "B00699ZDEY", manufacturer_id: manufacturer_4moms.id, category_id: category_babystroller.id, photo_url: "http://images.babyage.com/icons/localhost/products/large/4moms-origami-stroller-94220-762099796900002.jpg", description: "Power-Folding It's the world's first power-folding stroller: at the touch of a button, it folds itself. To open or close the stroller, just push that button and relax while the rest takes care of itself. Four Cup Holders With two cup holders in the handlebar and two more in the seat, there's plenty of room for water bottles, lattes, or sippy cups. Two-Step Fold So you won't do it by accident, folding the Origami takes two (easy) steps: turn the activation ring, then push the button. There's also a hidden lock switch to thwart those curious toddlers."}),
model_power = Model.create({ name: 'Origami Power-Folding Stroller', model_number: "B006POY0CO", manufacturer_id: manufacturer_4moms.id, category_id: category_babystroller.id, photo_url: "http://www.ubergizmo.com/wp-content/uploads/2012/03/origami-stroller.jpg", description: "The Origami is the world's first power-folding stroller: at the touch of a button, it folds itself. It's also the world's first cell phone-charging, mileage-counting, LCD-sporting stroller, with generators in the rear wheels that charge the stroller as you walk. Plus, the Origami has daytime running lights, pathway lights for low-light conditions, and sensors that detect when a child's in the seat (so it'll never fold by accident). From power folding to cell phone charging, it's everything a stroller should be."}),
model_pliko = Model.create({ name: 'Pliko Four', model_number: "IPPJ28US34UT53PG53", manufacturer_id: manufacturer_pegperego.id, category_id: category_babystroller.id, photo_url: "http://ecx.images-amazon.com/images/I/816O%2BIu8GvL._SL1500_.jpg", description: "Joining two perfect worlds, the Pliko Four combines a full featured stroller and a compact stroller, into one. New four-wheel design with 12-ball bearings and suspension allows for a smoother ride and enhanced maneuverability. The one-hand fold allows quick closing and a handle for carrying ease. "}),
model_switch = Model.create({ name: 'Switch Four', model_number: "IPSD30US34UT53PG53", manufacturer_id: manufacturer_pegperego.id, category_id: category_babystroller.id, photo_url: "http://www.baby-koo.com/images/detailed/4/switch_four_stroller_pois_grey.jpg", description: "The Switch Four closes easily without the seat or with the seat attached in either stroller or carriage mode. New four-wheel design with 12 ball bearings and suspension allows for a smoother ride and enhanced maneuverability. Now includes a coordinating foot muff and rain shield. The detachable cup holder and telescoping handles are two more features you will love."}),
model_aria = Model.create({ name: 'Aria Twin Stroller', model_number: "IPAX04NA34DA44GT44", manufacturer_id: manufacturer_pegperego.id, category_id: category_babystroller.id, photo_url: "http://img2.timeinc.net/people/i/cbb/2008/01/08/pegperegoariatwin.jpg", description: "The redesigned 2010 aria twin 60/40 is the ideal solution for parents with children of different ages. This innovative, side-by-side system offers a unique split-seat configuration. The aria twin is travel system-compatible - the perego primo Viaggio sip 30/30 car seat can be attached to the '60' side with the stroller's retractable anchors. The '40' side has a comfortable seat for big brother or sister"})

puts "models created"

User.destroy_all

user_sarah = User.create({email: "sarah@test.com", password_digest: "a", first_name: "Sarah", last_name: "Smith", address: "15 N. Michi Ave", address2: "Apt 27", city: "Chicago", state: "IL", zip_code: "60601"})
user_jill = User.create({email: "jill@test.com", password_digest: "b", first_name: "Jill", last_name: "Scott", address: "15 N. Michi Ave", address2: "Apt 28", city: "Chicago", state: "IL", zip_code: "60601"})
user_maria = User.create({email: "maria@test.com", password_digest: "c", first_name: "Maria", last_name: "Rivera", address: "15 N. Michi Ave", address2: "Apt 29", city: "Chicago", state: "IL", zip_code: "60601"})
user_jessica = User.create({email: "jessica@test.com", password_digest: "d", first_name: "Jessica", last_name: "Rabbit", address: "15 N. Michi Ave", address2: "Apt 30", city: "Chicago", state: "IL", zip_code: "60601"})
user_beyonce = User.create({email: "beyonce@test.com", password_digest: "e", first_name: "Beyonce", last_name: "Carter", address: "15 N. Michi Ave", address2: "Apt 31", city: "Chicago", state: "IL", zip_code: "60601"})

puts "user"

Listing.destroy_all

Listing.create({ model_id: model_ironman.id, photo_url: "http://gearjunkie.com/images/713.jpg", category_id: category_babystroller.id, manufacturer_id: manufacturer_bob.id, lender_description: "Few scratches", user_id: user_beyonce.id})
Listing.create({ model_id: model_ironman.id, photo_url: "http://i1128.photobucket.com/albums/m488/onesmileymonkey/bob1.jpg", category_id: category_babystroller.id, manufacturer_id: manufacturer_bob.id, lender_description: "Great condition", user_id: user_jessica.id})
Listing.create({ model_id: model_ironman.id, photo_url: "http://i2.squidoocdn.com/resize/squidoo_images/-1/draft_lens18061563module150974254photo_1308592093bob-strollers.jpg", category_id: category_babystroller.id, manufacturer_id: manufacturer_bob.id, lender_description: "Ready to Try today", user_id: user_jill.id})
Listing.create({ model_id: model_ironman.id, photo_url: "https://shop.sunrisecyclery.com/item-picture/15937/picture", category_id: category_babystroller.id, manufacturer_id: manufacturer_bob.id, lender_description: "Fantastic stroller!", user_id: user_maria.id})
Listing.create({ model_id: model_ironman.id, photo_url: "http://www.bikesonline.com/blog/wp-content/uploads/2011/08/BT1224.jpg", category_id: category_babystroller.id, manufacturer_id: manufacturer_bob.id, lender_description: "Loved it!", user_id: user_sarah.id})

puts "listing created"
